name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get install -y software-properties-common meson ninja-build
          sudo apt-get install -y --no-install-recommends wine64-tools
          echo "/usr/lib/wine" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./package-release.sh prod

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wine-nvoptix
          path: prod/nvoptix
          if-no-files-found: error
